compatibility_date = "2023-05-07"
compatibility_flags = ["streams_enable_constructors"]

# kv_namespaces = [
#   {binding = "SESSION_KV", id = "...", preview_id = "..." }
# ]

# [[ d1_databases ]]
# binding = "DB"
# database_name = "mydb"
# database_id = "mydb-id"