name = "remix-d1-drizzle"
compatibility_date = "2023-04-30"
compatibility_flags = ["streams_enable_constructors"]

[[ d1_databases ]]
binding = "DB"
database_name = "dzltest"
database_id = "ab8b338d-2bdb-4c24-9f8e-1095dc814506"
