compatibility_date = "2023-07-10"
compatibility_flags = []

# kv_namespaces = [
#   {binding = "SESSION_KV", id = "...", preview_id = "..." }
# ]

# [[ d1_databases ]]
# binding = "DB"
# database_name = "mydb"
# database_id = "mydb-id"